[build]
builder = "nixpacks"
watchPatterns = ["client/**", "proxy-server.js", "package.json"]
buildCommand = "npm install && npm run build:client"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 20