[build]
builder = "nixpacks"
watchPatterns = ["client/**", "package.json", "Dockerfile"]
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 20