[build]
builder = "nixpacks"
watchPatterns = ["client/**", "package.json"]
buildCommand = "npm install && npm run build --prefix client"

[deploy]
startCommand = "npm start --prefix client"
healthcheckPath = "/"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 20